POST http://localhost:3333/videos 
Content-Type: application/json

{
  "title": "video node",
  "description": "esses é o video 01",
  "duration": 180
}

###
GET http://localhost:3333/videos

###
PUT http://localhost:3333/videos/c381b0ef-a28b-4e28-a30d-ebe74a72fb0e
Content-Type: application/json

{
  "title": "video 02",
  "description": "esses é o video 02",
  "duration": 180
}

###

DELETE http://localhost:3333/videos/c381b0ef-a28b-4e28-a30d-ebe74a72fb0e
